### ISSUE TITLE
CSV file missing when preprocessing the data

### ISSUE THREAD

**Issue by 121898** [dipjyoti92/SC-WaveRNN#3]
Hi, 
         Thanks for this open-source implementation!
         It seems that the original vctk dataset doesn't have the csv file to generate the input for the tacotron training, could you please provide the one you are using?
        Another thing is that I didn't find the "gen_tacotron_spk_embed.py" you mentioned in README.

Thanks a lot!

**Comment by dipjyoti92** [comment]
transcription is provided in .csv. You will need to create your own .csv depending on the database you use. If you are using ljspeech, the metadata.csv would be the one that comes with the database. Then, just change the function nick to ljspeech in [here](https://github.com/dipjyoti92/SC-WaveRNN/blob/9b1211f3af036b7d2a16ed0f61e47057f169dfb7/preprocess.py#L58).

This .csv file consists of one record per line, delimited by the pipe character (0x7c). The fields are:
ID: this is the name of the corresponding .wav file
Transcription: words spoken by the reader (UTF-8)
Normalized Transcription: transcription with numbers, ordinals, and monetary units expanded into full words (UTF-8).

I changed the REAME. Thanks for pointing that out.
