### ISSUE TITLE
Minimum hours of data required for fine-tuning for a single unseen speaker

### ISSUE THREAD

**Issue by balag59** [dipjyoti92/SC-WaveRNN#4]
Thank you for your amazing work!!
For the TTS task, assuming that the synthesizer(Tacotron2) + vocoder has already been trained on a significant number of speakers, what would be the minimum amount of data that would be required to fine-tune the vocoder to a new unseen speaker? Would 5-10 hours be sufficient? Would be helpful to have an approximate amount. Just to add more details, this is for TTS in Hindi and I plan to train Tacotron2 + SC-WaveRNN on ~150 hours of Hindi data with several 100s of speakers before fine-tuning on a new unseen speaker. Thanks!

**Comment by dipjyoti92** [comment]
Generally, the Tacotron module needs more training data compared to WaveRNN. I see that you have 150 hours of Hindi data to pre-train the data. If the linguistic and acoustic variabilities are enough in these 150 hours of data, then you may need ~1 hours to fine-tune the module on a new unseen speaker (Alteast in English, I have found this in my experiments).

**Comment by balag59** [comment]
Thank you so much! That makes things clear.
