### ISSUE TITLE
need speaker_embedding in gen_wavernn.py

### ISSUE THREAD

**Issue by Rongjiehuang** [dipjyoti92/SC-WaveRNN#5]
Hi, I have some questions about this work.
In function gen_from_file of gen_wavernn.py, we need to input speaker_embedding extracted by wav. But actually, we only get mel-spectrogram for vocoder in TTS system to generate waveforms. Under such circumstances, how can we get speaker_embedding? Thank you.

**Comment by dipjyoti92** [comment]
In the zero-shot TTS pipeline, you need to provide a reference speech from which the TTS system will gather the speaker identity and feed it to the system. So, you can get speaker embeddings from the reference speech through the speaker encoder module.

**Comment by Rongjiehuang** [comment]
I see, thank u.
