### ISSUE TITLE
package error

### ISSUE THREAD

**Issue by xynulgm6020** [dipjyoti92/SC-WaveRNN#6]
my problem:
![image](https://user-images.githubusercontent.com/51982148/135787215-7e9b7fec-15e8-44c5-8786-8b939cb82d8e.png)
my settings:
![image](https://user-images.githubusercontent.com/51982148/135787285-7c75d824-3b89-47e9-ba1b-6093fb32d8f5.png)
my pythorch :
![image](https://user-images.githubusercontent.com/51982148/135787334-6eff65de-496b-43d0-8630-db2baa2d912f.png)
I need a gentleman to help me

**Comment by dipjyoti92** [comment]
@xynulgm6020 Please install torch properly.

**Comment by xynulgm6020** [comment]
> @xynulgm6020 Please install torch properly.

I solved this question ,thanks a lot
